version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-credentials/docker_registry_url

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r simple-python-app/requirements.txt
  build:
    commands:
      - echo "Building docker image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin https://index.docker.io/v1/
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" ./simple-python-app
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
  post_build:
    commands:
      - echo "Build complete"
      - echo "=== ls ==="
      - ls -l
      - echo "=== ls scripts ==="
      - ls -l scripts || echo "scripts folder missing!"
      - cat appspec.yml || echo "appspec.yml missing!"

artifacts:
  base-directory: .
  files:
    - appspec.yml
    - scripts/stop_container.sh
    - scripts/start_container.sh
